Discord
DISCORD_TOKEN=TOKEN_AICI
DISCORD_GUILD_ID=ID_SERVER_AICI
DISCORD_CHAT_CHANNEL_ID=ID_CANAL_CHAT
DISCORD_ANNOUNCE_CHANNEL_ID=ID_CANAL_ANUNTURI
DISCORD_TICKET_CHANNEL_ID=ID_CANAL_TICKETE
DISCORD_ADMIN_ROLE=Admin

Minecraft RCON
MC_HOST=178.83.113.160
MC_RCON_PORT=25575
MC_RCON_PASSWORD=skullsmp123
MC_QUERY_PORT=10004

Backend
BACKEND_HOST=0.0.0.0
BACKEND_PORT=8000
BACKEND_SECRET=schimba_asta_cu_ceva_random
